services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: Password123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-auth

  yourtripadvisor:
    image: yourtripadvisor
    build: ./keycloak
    container_name: yourtripadvisor
    ports:
      - '8081:8081'
    networks:
      - keycloak-auth
    depends_on:
      - postgres
      - keycloak

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    restart: always
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: Password123
      KC_HOSTNAME_URL: https://keycloak.yourtripadvisor.am
      KC_HOSTNAME_STRICT_HTTPS: "true"
      KC_HOSTNAME_STRICT_BACKCHANNEL:
      KC_PROXY: edge
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Password123
      KEYCLOAK_FRONTEND_URL: "https://keycloak.yourtripadvisor.am/auth"
    ports:
      - "8443:8443"
      - "8890:8080"
    networks:
      - keycloak-auth
    depends_on:
      - postgres
    command: start
volumes:
  postgres_data:
    driver: local

networks:
  keycloak-auth:
    driver: bridge