services:
  keycloak_demo:
    image: quay.io/keycloak/keycloak:24.0.3
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_keycloak_demo
      KC_DB_URL_DATABASE: keycloak
      KC_DB_PASSWORD: password
      KC_DB_USERNAME: keycloak
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_PROXY: edge
      KC_HOSTNAME_ADMIN_URL: https://keycloak.yourtripadvisor.am
      KC_HOSTNAME_URL: https://keycloak.yourtripadvisor.am
    ports:
      - "8890:8080"  # Adjusted to default Keycloak port if necessary
    depends_on:
      postgres_keycloak_demo:
        condition: service_healthy
    networks:
      - keycloak_demo_dev_network

  postgres_keycloak_demo:
    image: postgres:14.2
    command: postgres -c 'max_connections=200'
    volumes:
      - pgdata_keycloak_demo:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak  # Changed from POSTGRES_USERNAME
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5436:5432"
    networks:
      - keycloak_demo_dev_network

  ai-model:
    build:
      context: ./src/AIModel
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - ai-network

volumes:
  pgdata_keycloak_demo:

networks:
  keycloak_demo_dev_network:
    driver: bridge
  ai-network: